[Refactor] 나의 활동 뷰, 카드 생성 및 공유 뷰 코드 리팩토링
SW-TeleToby/BlueCombing pull request #35
Opened 2022-10-16 09:55 UTC by hs-ryu

# 배경
급하게 짜느라 중복된 코드가 존재했고, 뷰 바디 부분이 길어져 한눈에 보기 힘들어 관련하여 리팩트링 진행하였습니다.

# 상세 내역
### 공통
- 뱃지 설명과 이미지 관련하여 스위치 문을 산발적으로 사용했던 부분을 열거형으로 통합시켰습니다.
- 각 뷰에서, 바디 부분에 한꺼번에 코드를 짰던 것을 각 컴포넌트별로 구분하였습니다.
- 크기 지정을 위해 프레임을 많이 사용했던것과 관련하여, 특정 부분(이미지 크기)을 제외하곤 최대한 없애려고 노력했습니다.
- 필요없는 주석은 최대한 삭제했습니다.
- 토비가 맵쪽에서 이동거리, 이동시간 등을 따로 모델로 뺀 것을 확인했습니다. 그것을 활용하여 이 PR이 머지 된 이후 제가 작성했던 CardViewModel에서 public static 변수들을 없앨 것입니다.
### 카드 생성 부분
- 경로 이미지가 깨지는 것을 수정했습니다. 간단한 작업이라 코드 한줄 추가했습니다.

# 테스트 방법
기능 적으로 개선하지 않았습니다. 경로 이미지가 깨지지 않도록만 만들어 놓았습니다.

# 스크린샷
- 이전
![IMG_0359](https://user-images.githubusercontent.com/75309495/196029135-bab6a02c-3aef-46b8-8da5-3d3dcebebb8d.PNG)
- 이후
![IMG_0358](https://user-images.githubusercontent.com/75309495/196029131-5800019d-7e3c-4dc6-a2e0-347fee484af4.PNG)

2022-10-16 11:57 UTC, E-know commented on BlueCombing/Views/MakeCardViews/BadgeDescription.swift
> +}
extention은 따로 뺴주시는게 좋을 것 같습니다.

2022-10-16 11:57 UTC, E-know commented on BlueCombing/Views/MakeCardViews/BadgeDescription.swift
> +    }
함수명이 어떤 것을 이야기하고자 하는 것인지 명확하게 안드러나는 것 같습니다.
함수명 시작은 동사형으로 변경부탁드립니다.

2022-10-16 11:57 UTC, E-know commented on BlueCombing/Views/MakeCardViews/BadgeDescription.swift
> +    }
또한 default 와 산호초가 같은 변환값을 갖고 있는데 특별한 이유가 있을까요?

2022-10-16 11:57 UTC, E-know commented on BlueCombing/Views/MakeCardViews/BadgeDescription.swift
> +enum BadgeDescription {
```suggestion
enum BadgeDescription: String {
```
어떤 반환형 인지 써주면 좋을 것 같습니다.

2022-10-16 11:57 UTC, E-know commented on BlueCombing/Views/MakeCardViews/BadgeDescription.swift
> +    }
[String] 형태에서 ArraySlice<String> -> Array<String> 으로 변환되는 이유가 있을까요?

2022-10-16 11:57 UTC, E-know commented on BlueCombing/Views/MakeCardViews/CardView.swift
> +//}
필요 없는 주석은 삭제 해주세요.
```suggestion
```

2022-10-16 11:57 UTC, E-know commented on BlueCombing/Views/MakeCardViews/MakeCardView.swift
> +                cardViewModel.newCard.badge = presentBadge.badgeImage
View 에서 로직이 돌아가는 것보다는 ViewModel에서 로직이 돌아가는게 좋아보입니다.

2022-10-16 11:57 UTC, E-know commented on BlueCombing/Views/MyActivityView/BadgeGradeView.swift
> +            Spacer().frame(width: 20)
```suggestion
            Text("비치코밍 등급")
                .font(.Body3)
            Spacer()
            Spacer()
                .frame(width: 20)
```
어떤 것은 바로 . 뒤에 함수를 어떤 것을 줄을 바꿔서 호출을 하고 있습니다. 통일되게 부탁드립니다.

2022-10-16 11:57 UTC, E-know commented on BlueCombing/Views/MyActivityView/BadgeGradeView.swift
> +                            .background(Color.combingBlue2)
이것도 마찬가지로 가독성을 위해서 통일되게 부탁드립니다.

2022-10-16 11:57 UTC, E-know commented on BlueCombing/Views/MyActivityView/DetailSheetView.swift
> +                    print(shareImageView)
필요 없는 print문은 삭제해주세요.

2022-10-16 11:57 UTC, E-know commented on BlueCombing/Views/MyActivityView/MyActivityView.swift
> +    @State var badgeImage: UIImage = UIImage(named: "img_badge_coral")!
```suggestion
    @State var badgeImage: = UIImage(named: "img_badge_coral")!
```
이 부분은 충분하게 선언으로 자료형을 알 수 있음으로 자료형을 명시할 필요가 없을 것 같습니다!

2022-10-16 11:57 UTC, E-know commented on BlueCombing/Views/MyActivityView/MyActivityView.swift
> +            .padding(.bottom)
이 부분은 padding이 중복되서 들어가는데 이유가 있을까요?

2022-10-16 11:57 UTC, E-know commented on BlueCombing/Views/MyActivityView/MyActivityView.swift
> +            .padding(.trailing,20)
이것도 마찬가지로 가독성을 위해서 줄 나란히 부탁드립니다.

2022-10-16 11:57 UTC, E-know commented on BlueCombing/Views/MyActivityView/BadgeGradeView.swift
> +            badgeImage = badge.badgeImage
description 및 이미지에 대한 로직이 ViewModel로 뺴는 것은 어떨까요?

2022-10-16 13:38 UTC, hs-ryu commented on BlueCombing/Views/MakeCardViews/BadgeDescription.swift
> +}
따로 뺐습니다!

2022-10-16 13:41 UTC, hs-ryu commented on BlueCombing/Views/MakeCardViews/BadgeDescription.swift
> +    }
사실 현재 다른 케이스가 존재하지 않아서 디폴트 값은 필요 없습니다. 단지, 최초 앱 사용시부터 뱃지는 산호초로 가지고 있기 때문에 디폴트로 두는게 나을것 같아 설정했습니다.

2022-10-16 13:45 UTC, hs-ryu commented on BlueCombing/Views/MakeCardViews/BadgeDescription.swift
> +enum BadgeDescription {
딱히 반환값이 필요 없어, 타입을 쓰지 않았었습니다! 조언해주신대로 반환형 추가하여 커밋했습니다.

2022-10-16 13:57 UTC, hs-ryu commented on BlueCombing/Views/MakeCardViews/BadgeDescription.swift
> +    }
내 등급을 확인하는 뷰에서는 이전에 획득한 뱃지 정보 또한 표시해야합니다. 하지만 현재 파이어베이스에 "본인의 현재 뱃지"만 저장하고 있습니다. 따라서 이전에 획득한 뱃지들을 표시하기 위해선 작성한 코드처럼 배열에서 슬라이싱 해서 표시하는 방식이 가장 간편하다고 판단했습니다. swift에서는 슬라이싱을 위해선 ArraySlice타입으로 사용해야 하는 것으로 알고 있습니다. 유저 모델에서 뱃지 배열은 배열 형식으로 되어있어, 위 방식 말고는 해결 방식을 찾지 못했습니다. 혹시 더 좋은 방법이 있을까요?

2022-10-16 14:00 UTC, hs-ryu commented on BlueCombing/Views/MyActivityView/DetailSheetView.swift
> +                    print(shareImageView)
감사합니다! 다른 파일에서도 필요없는 프린트 문이 있어 함께 삭제했습니다!

2022-10-16 14:00 UTC, hs-ryu commented on BlueCombing/Views/MakeCardViews/BadgeDescription.swift
> +    }
함수명은 동사형으로 변경하였습니다!

2022-10-16 14:20 UTC, hs-ryu commented on BlueCombing/Views/MakeCardViews/CardView.swift
> +//}
삭제했습니다! 감사합니다!

2022-10-16 14:22 UTC, hs-ryu commented on BlueCombing/Views/MakeCardViews/CardView.swift
> +//}
다른 부분에도 필요없는 주석 남아 있길래 역시 삭제했습니다!

2022-10-16 14:24 UTC, hs-ryu commented on BlueCombing/Views/MyActivityView/MyActivityView.swift
> +    @State var badgeImage: UIImage = UIImage(named: "img_badge_coral")!
말씀해 주신 부분 수정 했습니다. 하나 여쭤보고 싶은게 있는데, 혹시 자료형을 명시하고 명시하지 않고 에 대한 기준이 따로 있을까요??

2022-10-16 14:47 UTC, hs-ryu commented on BlueCombing/Views/MyActivityView/MyActivityView.swift
> +            .padding(.bottom)
미쳐 체크하지 못했던 부분이네요! 필요없는 부분이라 삭제했습니다!

2022-10-16 14:51 UTC, hs-ryu commented on BlueCombing/Views/MyActivityView/MyActivityView.swift
> +            .padding(.trailing,20)
세세하게 봐주셔서 너무 감사합니다! 얼라인 맞춰서 올리겠습니다!

2022-10-16 14:52 UTC, DevLuce reviewed
이 PR 맛집이네요 토비 의견 동의합니다

2022-10-16 15:10 UTC, hs-ryu commented on BlueCombing/Views/MyActivityView/BadgeGradeView.swift
> +            badgeImage = badge.badgeImage
description과 badgeImage는 CardViewModel에 넣어야 하는 파라미터 인 것 같습니다. 현재 해당 뷰에서는 CardViewModel을 받지 않고 있습니다. 상위 뷰인 MyActivityView로 부터 ViewModel을 전달 받아 사용해야할 것 같은데, 이 방법대로 적용하는것이 더 괜찮아 보이신다는 것으로 이해해도 괜찮을까요?

2022-10-16 15:13 UTC, E-know commented on BlueCombing/Views/MakeCardViews/BadgeDescription.swift
> +    }
필요 없는 값을 default 값을 지정하는 것은 나중에 추적하기 힘들다고 생각합니다.

2022-10-16 15:17 UTC, E-know commented on BlueCombing/Views/MakeCardViews/BadgeDescription.swift
> +    }
```
switch self {
      case .coral:
          return Array(badgeList[0...0])
      }
  }
```
이러한 형태는 어떠한가요?
한눈에 보기에 편하고 직관적이라고 생각됩니다.

2022-10-16 15:39 UTC, E-know commented on BlueCombing/Views/MyActivityView/MyActivityView.swift
> +    @State var badgeImage: UIImage = UIImage(named: "img_badge_coral")!
Swift는 설계에 의한 안정성에 의해서 타입이 명확하다면 명시하지 않도록 설계된 언어로 알고 있습니다.

또한 코드 가독성 측면에서도 자료형을 누가봐도 알 수 있다면 안 적는 것이 좋다고 알고 있습니다.

2022-10-16 15:41 UTC, E-know commented on BlueCombing/Views/MyActivityView/BadgeGradeView.swift
> +            badgeImage = badge.badgeImage
뷰 모델 전체가 파라미터로 받는다는 것은 뷰모델에 대한 의존성이 너무 커지는 것 같습니다.
코드 전체를 봤을 때 위와 비슷한 코드가 반복되고 있는것 같은데 맞나요?

2022-10-17 02:35 UTC, hs-ryu commented on BlueCombing/Views/MyActivityView/MyActivityView.swift
> +    @State var badgeImage: UIImage = UIImage(named: "img_badge_coral")!
그렇군요! 감사합니다!

2022-10-17 02:57 UTC, hs-ryu commented on BlueCombing/Views/MakeCardViews/BadgeDescription.swift
> +    }
한수 배웠습니다! 훨씬 깔끔해지는군요. 수정해서 올렸습니다.

2022-10-17 03:08 UTC, hs-ryu commented on BlueCombing/Views/MakeCardViews/BadgeDescription.swift
> +    }
이해했습니다. 수정하여 다시 올렸습니다!

2022-10-17 03:28 UTC, hs-ryu commented on BlueCombing/Views/MyActivityView/BadgeGradeView.swift
> +            badgeImage = badge.badgeImage
맞습니다. 위와 같은 코드가 다른 View에서도 하나 동일하게 사용되고 있습니다.

2022-10-17 14:28 UTC, hs-ryu commented on BlueCombing/Views/MyActivityView/BadgeGradeView.swift
> +            badgeImage = badge.badgeImage
<img width="625" alt="스크린샷 2022-10-17 오후 11 26 45" src="https://user-images.githubusercontent.com/75309495/196203643-416d3ec3-d64b-4de3-b901-59127a9cd38a.png">

말씀해주신 부분 적용하여, 위 이미지 처럼 뷰 모델로 작성해서 빼 보았습니다. 훨씬 코드가 간략해져서 좋은 것 같습니다.

2022-10-17 16:12 UTC, E-know requested changes

2022-10-17 16:12 UTC, E-know commented on BlueCombing/ViewModels/BadgeViewModel.swift
> +    @Published var badgeImage: UIImage = UIImage(named: "img_badge_coral")!
이 부분 역시 자료형 선언을 불필요해보입니다.

2022-10-17 16:12 UTC, E-know commented on BlueCombing/ViewModels/CardViewModel.swift
> +    @Published var newCard = Card(id: 0, distance: 0, time: 0, location: "포항시 영일대 해수욕장", backgroundImage: UIImage(named: "img_card_default")!, badge: UIImage(named: "img_badge_coral")!)
강제 언래핑은 피해주세요.

2022-10-17 16:12 UTC, E-know commented on BlueCombing/Views/MakeCardViews/CardView.swift
> +            .padding(.bottom, 30)
가독성을 위해서 통일시켜 주세요.
```suggestion
        }
            .padding(.leading, 30)
            .padding(.bottom, 30)
```

2022-10-17 16:12 UTC, E-know commented on BlueCombing/Views/MakeCardViews/MakeCardView.swift
> +            .padding(.bottom, 10)
```suggestion
        }
            .padding(.vertical, 10)
            .padding(.bottom, 10)
```
가독성을 위해서 통일시켜 주세요.

2022-10-17 16:12 UTC, E-know commented on BlueCombing/Views/MakeCardViews/MakeCardView.swift
> +    }
tab이 여러번 중복된 것 같습니다.

2022-10-17 16:12 UTC, E-know commented on BlueCombing/Views/MakeCardViews/MakeCardView.swift
> +                }
빈 클로져는 한 줄로 작성이 좋아보입니다.
```suggestion
                Button("나중에 하기") {  }
```

2022-10-17 16:20 UTC, hs-ryu commented on BlueCombing/ViewModels/CardViewModel.swift
> +    @Published var newCard = Card(id: 0, distance: 0, time: 0, location: "포항시 영일대 해수욕장", backgroundImage: UIImage(named: "img_card_default")!, badge: UIImage(named: "img_badge_coral")!)
옵셔널로 선언해서 사용하라는 말씀이시죠???

2022-10-17 16:22 UTC, E-know commented on BlueCombing/ViewModels/CardViewModel.swift
> +    @Published var newCard = Card(id: 0, distance: 0, time: 0, location: "포항시 영일대 해수욕장", backgroundImage: UIImage(named: "img_card_default")!, badge: UIImage(named: "img_badge_coral")!)
guard를 사용해서 언래핑이나 ?? 를 통해서 래핑이 좋아보입니다!

2022-10-17 16:27 UTC, hs-ryu commented on BlueCombing/ViewModels/CardViewModel.swift
> +    @Published var newCard = Card(id: 0, distance: 0, time: 0, location: "포항시 영일대 해수욕장", backgroundImage: UIImage(named: "img_card_default")!, badge: UIImage(named: "img_badge_coral")!)
감쟈합니다! 다시 작성해보겠습니다!

2022-10-17 16:28 UTC, hs-ryu commented on BlueCombing/ViewModels/BadgeViewModel.swift
> +    @Published var badgeImage: UIImage = UIImage(named: "img_badge_coral")!
끅. 한번 말씀해 주셨던걸 금방 까먹었군요. 죄송합니다

2022-10-17 16:28 UTC, hs-ryu commented on BlueCombing/Views/MakeCardViews/CardView.swift
> +            .padding(.bottom, 30)
보는 김에, 다른 부분도 이렇게 되있는 부분이 없나 다시한번 체크했습니다. 감사합니다.

2022-10-17 16:28 UTC, hs-ryu commented on BlueCombing/Views/MakeCardViews/MakeCardView.swift
> +            .padding(.bottom, 10)
위 이슈를 해결하며 같이 해결했습니다!

2022-10-17 16:29 UTC, hs-ryu commented on BlueCombing/Views/MakeCardViews/MakeCardView.swift
> +    }
제가 작성한 파일 돌아다니면서 control + i 명령으로 다시한번 얼라인을 조정했습니다. 감사합니다.

2022-10-17 16:30 UTC, hs-ryu commented on BlueCombing/Views/MakeCardViews/MakeCardView.swift
> +                }
수정했습니다!!

2022-10-17 16:32 UTC, hs-ryu commented on BlueCombing/ViewModels/CardViewModel.swift
> +    @Published var newCard = Card(id: 0, distance: 0, time: 0, location: "포항시 영일대 해수욕장", backgroundImage: UIImage(named: "img_card_default")!, badge: UIImage(named: "img_badge_coral")!)
<img width="452" alt="스크린샷 2022-10-18 오전 1 31 29" src="https://user-images.githubusercontent.com/75309495/196232629-352aaf78-107a-453d-80aa-698502b8043d.png">

그럼 혹시 이런 부분들도 다 수정하는게 좋을까요??

2022-10-17 17:03 UTC, hs-ryu commented on BlueCombing/ViewModels/CardViewModel.swift
> +    @Published var newCard = Card(id: 0, distance: 0, time: 0, location: "포항시 영일대 해수욕장", backgroundImage: UIImage(named: "img_card_default")!, badge: UIImage(named: "img_badge_coral")!)
말씀해주신 부분에 대해 시도해 보고 있는데 살짝 어렵습니다. 

<img width="764" alt="스크린샷 2022-10-18 오전 2 02 29" src="https://user-images.githubusercontent.com/75309495/196238999-93d6860e-19db-4b38-870d-bfac19d18529.png">

위 방향으로 진행하는 것이 맞을까요?

2022-10-17 17:13 UTC, E-know commented on BlueCombing/ViewModels/CardViewModel.swift
> +    @Published var newCard = Card(id: 0, distance: 0, time: 0, location: "포항시 영일대 해수욕장", backgroundImage: UIImage(named: "img_card_default")!, badge: UIImage(named: "img_badge_coral")!)
```
@Published var newCard: Card {
    guard let backgroundImage = UIImage(naemd: "img_card_default"), let badgeImage = UIImage(named: "img_card_default") else { return 이미지가 못불러왔을 때의 이미지 }
    return Card(id: 0, distance: 0, time: 0, location: "포항시 영일대 해수욕장", backgroundImage: backgroundImage, badge: badgeImage)
}

```
위와 같이 클로져 형태는 어떤가요? 

적다보니 backgroundImage와 badge 둘다 Image를 불러오고 있는데
`badge` -> `badgeImage`가 더 어울리지 않을까 싶습니다.

또한 Card가 View 인가요? 혹은 데이터인가요? Card를 읽었을 때에 어떤 것을 지칭하는지 와 닿지가 않습니다.

2022-10-18 13:34 UTC, hs-ryu commented on BlueCombing/ViewModels/CardViewModel.swift
> +    @Published var newCard = Card(id: 0, distance: 0, time: 0, location: "포항시 영일대 해수욕장", backgroundImage: UIImage(named: "img_card_default")!, badge: UIImage(named: "img_badge_coral")!)
Card 모델은 Card에 들어가는 데이터들을 담고 있는 데이터입니다. 헷갈릴 수 있겠군요. 수정을 하도록 하겠습니다!
말씀해주신 클로져 형태는 생각해보지 못했던 방식이네요. 적용해보도록 하겠습니다!

2022-10-18 13:57 UTC, hs-ryu commented on BlueCombing/ViewModels/CardViewModel.swift
> +    @Published var newCard = Card(id: 0, distance: 0, time: 0, location: "포항시 영일대 해수욕장", backgroundImage: UIImage(named: "img_card_default")!, badge: UIImage(named: "img_badge_coral")!)
<img width="803" alt="image" src="https://user-images.githubusercontent.com/75309495/196450481-3acae7d1-fd71-455d-9ad7-1652723f1cfd.png">
제안해 주신 방법으로 진행해 보았지만, 위와 같은 문제를 해결하지 못해 아래와 같은 방법을 제안해 봅니다. SF symbol에 있는 이미지를 가지고 오는 방식입니다. 
<img width="805" alt="image" src="https://user-images.githubusercontent.com/75309495/196449776-119951c6-7c8d-45f3-9caf-982cc7586a74.png">

2022-10-18 14:09 UTC, hs-ryu commented on BlueCombing/ViewModels/CardViewModel.swift
> +    @Published var newCard = Card(id: 0, distance: 0, time: 0, location: "포항시 영일대 해수욕장", backgroundImage: UIImage(named: "img_card_default")!, badge: UIImage(named: "img_badge_coral")!)
아니면 모델에서 UIImage를 옵셔널로 선언해서 사용할까요?

2022-10-18 14:12 UTC, hs-ryu commented on BlueCombing/ViewModels/CardViewModel.swift
> +    @Published var newCard = Card(id: 0, distance: 0, time: 0, location: "포항시 영일대 해수욕장", backgroundImage: UIImage(named: "img_card_default")!, badge: UIImage(named: "img_badge_coral")!)
아래와 같은 방법은 어떤가요??
<img width="766" alt="image" src="https://user-images.githubusercontent.com/75309495/196455148-d8aae4f6-57de-4577-a43f-3144c31b4ebc.png">

2022-10-19 04:19 UTC, E-know commented on BlueCombing/Views/MyActivityView/BadgeGradeView.swift
> +            badgeImage = badge.badgeImage
위 코드의 UI코드 자료형 선언은 삭제해주세요!

2022-12-10 13:15 UTC, DevLuce approved these changes
LGTM!! 고생했어요

2022-12-11 14:44 UTC, merged